#!/usr/bin/env bash


limit=5
count=0
file=$1

echo "Converting $file"
while true; do
    if [ $count -ge $limit ]; then
        notify-send "Tried $count times" "Giving up at $file..."
        exit
    fi
    rm "$file.mp4"
    if ffmpeg -i "$file" -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 3.0 -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -acodec copy -movflags +faststart "$file.mp4"; then
        break
    fi
    echo "Failed $count times, trying again..."
    sleep 1
    count=$((count + 1))
done
cp "$file.mp4" "$file"
rm "$file.mp4"
echo -n "$file" | xclip -i -selection clipboard
notify-send "Recording $file finished" "Path was copied to clipboard"
