#!/bin/bash

# Check dependencies
soft[0]="curl"
soft[1]="xclip"
soft[2]="perl"
soft[3]="surl"
for check in ${soft[@]}; do if [[ ! -e "/usr/bin/$check" ]]; then echo "$check doesn't exists. Can't execute program."; exit 1;	fi; done

CHARS=$(python2 -c 'print u"\u0091\u0092\u00a0\u200E".encode("utf8")')

SERVICE='tinyurl.com'

function shortIt {
    echo -n "${1}" | surl
}


if [[ $1 == '-c' ]]; then
    clipboard=$(xclip -o -selection clipboard | sed 's/['"$CHARS"']//g')
    primary=$(xclip -o -selection primary | sed 's/['"$CHARS"']//g')

    if [[ ($(echo ${primary} | grep -c '^https*://.*$') -eq 1 || $(echo ${primary} | grep -c '^www\..*$') -eq 1) &&
             $(echo ${primary} | grep -c $SERVICE)        -eq 0 ]]; then
        # Se houver um link na seleção primária, utilizá-lo
        url=${primary}
    elif [[ ($(echo ${clipboard} | grep -c '^https*://.*$') -eq 1 || $(echo ${clipboard} | grep -c '^www\..*$') -eq 1) &&
             $(echo ${clipboard} | grep -c $SERVICE)        -eq 0 ]]; then
        # Senão, usar a área de transferência
        url=${clipboard}
    else
        # Se nenhum dos dois for um link, sair
        exit 1
    fi

    # Limpa o clipboard
    echo -n | xclip -selection clipboard

    # Shorts it
    out=$(echo -n "${url}" | surl -s $SERVICE)
    if [[ $? != 0 || ${out} == ${url} ]]; then
        echo "Some error happened. Bye."
        exit 1
    else
        echo -n "$out" | xclip -selection clipboard
    fi
elif [[ "${1}" =~ http ]]; then
    url=$(echo ${1} | sed 's/['"$CHARS"']//g')

    out=$(echo -n "${url}" | surl -s $SERVICE)
    if [[ $? != 0 || ${out} == ${url} ]]; then
        echo "Some error happened. Bye."
        exit 1
    else
        echo "$out"
    fi
else
    echo "Uso: shortenurl -c [URL]"
    echo
    echo "Encurta um link usando goo.gl."
    echo "Se -c for passado, pega o link da seleção primária ou da área de "
    echo "transferência e copia o resultado para a área de transferência."
    exit 1
fi

