#!/bin/bash

# Check dependencies
soft[0]="curl"
soft[1]="xclip"
soft[2]="perl"
for check in ${soft[@]}; do if [[ ! -e "/usr/bin/$check" ]]; then echo "$check doesn't exists. Can't execute program."; exit 1;	fi; done

CHARS=$(python2 -c 'print u"\u0091\u0092\u00a0\u200E".encode("utf8")')

clipboard=$(xclip -o -selection clipboard | sed 's/['"$CHARS"']//g')
primary=$(xclip -o -selection primary| sed 's/['"$CHARS"']//g')

if [[ ($(echo ${primary} | grep -c '^https*://.*$') -eq 1 || $(echo ${primary} | grep -c '^www\..*$') -eq 1) ]]; then
    # Saves primary clipboard URL to a file
    url=${primary}
    filename=${url%%\?*}
    filename="/tmp/"${filename##*/}
    wget "$url" -O "$filename" >/dev/null 2>&1
elif [[ ($(echo ${clipboard} | grep -c '^https*://.*$') -eq 1 || $(echo ${clipboard} | grep -c '^www\..*$') -eq 1) ]]; then
    # Saves clipboard URL to a file
    url=${clipboard}
    filename=${url%%\?*}
    filename="/tmp/"${filename##*/}
    wget "$url" -O "$filename" >/dev/null 2>&1
elif xclip -selection clipboard -t TARGETS -o | grep -qm1 'image/png'; then
    # Saves a copied image into a local image
    filename="$(mktemp -t "XXXXXX.png")"
    xclip -selection clipboard -t image/png -o > $filename
else
    exit 1
fi

echo "$filename"
# Clears clipboard and selects new URI
echo -n | xclip -selection clipboard
echo -n "$filename" | xclip -selection clipboard
